### ISSUE TITLE
Ingest uncatalogued images into Tandem Vault

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1016]
Preparatory work:

- [x] Create upload sets, one for each Miro prefix
- [x] Create collections, one for each Miro prefix
- [x] Create collections, one for each year of the Wellcome Image awards

Upload step:

- [x] Logic to determine if an image is a WIA, and if so, which year
- [x] Code for uploading an image from our S3 bucket into the Tandem Vault S3 bucket
- [x] Code for sorting an uploaded image into the Miro collection
- [x] Code for sorting an uploaded image into the WIA award collection, if necessary
- [x] Code for adding the appropriate Miro metadata to an asset

**Comment by kenoir** [comment]
See https://github.com/wellcometrust/platform/issues/1058 for WIA criteria.

**Comment by kenoir** [comment]
Talk to @alexwlchan about > Code for adding the appropriate Miro metadata to an asset

**Comment by jtweed** [comment]
```
year,collection
1997,110075
1998,110076
1999,110077
2001,110078
2002,110079
2005,110080
2006,110081
2008,110082
2009,110083
2011,110084
2012,110085
2014,110086
2015,110087
2016,110088
2017,110089
```

**Comment by kenoir** [comment]
@alexwlchan adds:

```py
import requests

resp = requests.put(
    'https://wellcome.tandemvault.com/api/v1/assets/2965980',
    params={
        'api_key': '0fd483ff51ba9dbea0bfe497b788594c2ce9578088cff6ecb9e33b87cda501e1',
        'asset[description]': 'First description by Alex',
        'asset[usage_terms]': 'These are my usage terms'
    }
)
resp.text
resp
```

**Comment by kenoir** [comment]
Two things remain:
- Provide a list of WIA winners from the enrichment queue.
- Provide a list of missing source files from the upload queue

**Comment by kenoir** [comment]
Calling this one done.
