### ISSUE TITLE
After-action review actions from API flakiness

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1304]
- [x] Fix the credit lines in the API (#1192)
- [x] Have alarms for healthy/unhealthy hosts (#1342)
- [x] Push non-critical alarms into a separate Slack channel (#1305)
- [ ] ~Create summaries of non-critical errors (#1367)~
- [ ] ~Automate Remus/Romulus deployments~ (#1316)
- [x] Terraform notifications in Slack (#1310)
- [x] Terraform warnings on production changes (#1306)

**Comment by alexwlchan** [comment]
Closing because we've done everything we're going to do for now; the two remaining items have been spun out as separate issues.
