### ISSUE TITLE
Implement service for storing graphs of matched works

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1405]
- [x] Matcher does nothing (#2054 )
- [x] Matcher finds links in a work update but doesn't have any past information (#2067 )
- [x] Matcher outputs linked works based on a work update and previously seen works (#2099)
- [x] Matcher stores work version and checks version before applying graph updates
- [ ] Matcher is able to handle concurrent updates with locks (#2207)
- [x] Matcher can break links (#2067 partially, #2099 )
