### ISSUE TITLE
Transform bibs and items, part 1

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1419]
This is the first set of low-hanging fruit from Silver's notes.

- [x] **wwork:identifiers**. Already working, we need to break it into a separate trait. (#1421)
- [x] **wwork:title**.
- [ ] ~**wwork:genres** and **wwork:subjects**, but only the concept – qualified concepts come later.~
- [x] **wwork:publicationDate** – passing the date straight through. Parsing it into a consistent format comes later. (#1599)
- [x] **wwork:placeOfPublication** – only the non-identified places. (#1648)
- [x] **wwork:publishers** – subfield 260 is already transformed, but not 264. ~Open Q: what if both 260 and 264 are populated?~ (#1429)
- [x] **wwork:lettering** – just use 264 indicator 16; don't worry about whether it’s an archive/image/journal (#1467)
- [x] **wwork:description** (#1444)
- [x] **wwork:extent** (#1632)
- [x] **wwork:physicalDescription** (#1629)
- [ ] **wwork:items** – we need to break it into a separate trait, and add a few extra fields (#1462, #1608, #1609)

Part of #1361.
