### ISSUE TITLE
Migrate the internal Sierra IDs to the correct scheme

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1639]
- [x] Modify the Sierra readers to write records with the 7-digit, no-prefix, no check-digit scheme (#1640)
- [x] Move all the rows in the SierraItems DynamoDB table to the 7-digit, no-prefix, no check digit scheme (#1642).
- [ ] Move all the rows in the SourceData DynamoDB table to the 7-digit, no-prefix, no check digit scheme (#1642, #1645)
- [ ] Move all the keys in the S3 bucket to match (#1645)
- [ ] Fix the contents of everything in the S3 bucket (#1645)
- [x] Modify the Sierra transformer to use two versions of Sierra IDs:
     - [x] `sierra-identifier` which is the raw id
     - [x] `sierra-system-number` which has the record type and check digit
- [x] Modify the Miro transformer to use two versions of Sierra IDs:
     - [ ] ~`sierra-identifier` which is the raw id~
     - [ ] `sierra-system-number` which has the record type and check digit

**Comment by jtweed** [comment]
Probably don't need `sierra-identifier` on Miro works.

**Comment by alexwlchan** [comment]
So, change of plan. We're going to go back to Sierra and reread everything, rather than trying to do any more database surgery.

**Comment by pollecuttn** [comment]
Can whoever goes back to Sierra let Louise Simon know when it's happening so she can be aware if there's any knock on effects to Sierra.

**Comment by alexwlchan** [comment]
I didn't manage to clear all the Sierra IDs from the SourceData table or the VHS buckets, so somebody else will need to do that first.

**Comment by alexwlchan** [comment]
Now we’ve reharvested all the Sierra data, I think this is done, modulo reindexes.
