### ISSUE TITLE
Improve test isolation

### ISSUE THREAD

**Issue by rgladwell** [wellcometrust/platform#1643]
A [recent ticket](https://github.com/wellcometrust/platform/pull/1612) revealed that many of our tests aren't properly isolated and share stateful objects and services like mocks and SQS queues.

We need to go through all the tests in each service and:

 1. Replace all occurrences of mutable variables with immutable ones.
 2. In cases where mutable variables are required, ensure interractions are thread-safe.
 3. Ensure instances of mocks are not shared between tests.
 4. Ensure all stateful, persistent resources (like SQS queues) are safely created and destroyed using the [loan-fixture](https://github.com/wellcometrust/platform/blob/2d5bb62f78715ff3ca7767482696f420aec911a5/common/src/test/scala/uk/ac/wellcome/test/fixtures/AkkaFixtures.scala) design pattern

We should go through each Scala sub-module and verify the above:

 - [x] api (#1714)
 - [x] common (#1656)
 - [x] id_minter (#1654)
 - [x] ingestor (#1665)
 - [x] recorder
 - [x] reindex_worker (#1712)
 - [x] sierra_adapter_common
 - [x] sierra_bib_merger (#1764)
 - [x] sierra_item_merger (#1764)
 - [x] sierra_items_to_dynamo (#1690)
 - [x] sierra_reader (#1708)
 - [x] transformer (#1667)

**Comment by alexwlchan** [comment]
The sierra-common tests don’t have any tests which need fixtures. That package does contain the VHSLocal, but we need to remove that in other tests first!

**Comment by alexwlchan** [comment]
The one outstanding thorn here is the API, which has a bunch of test classes that use a `server` instance a la ApiWorksTest.

In many of these tests, we're testing the public-facing behaviour – I don’t think we could do away with the server instance. If we had to start/stop a test every time, the tests could take noticeably longer (and tests would become spammier).

I had a go at this once (#1714), and I didn't manage to finish it – the tests were hanging, but Travis couldn't tell me why.
