### ISSUE TITLE
Transform bibs and items, part 2

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1682]
This is a tracking ticket for the new transformations we agreed in backlog refinement today. In priority order (most important first):

* [x] workType (see also: #787, #1688)
* [x] creators (see also: #1724 , #1698 , #1528)
* [x] contributors (#1917, #1920, #1925)
* [x] genres and subjects (#1938)
* [x] lettering (see also: #1673)
* [x] language (#1699)
* [x] dimensions (#1733)

---

* [x] Reindex Miro and Sierra source data into new index.
* [ ] Reindex source data into new indices for the contributor changes
