### ISSUE TITLE
V1 Catalogue API with updatable Miro data

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#1840]
So the general gist is that we’re going to have two indexes, and the API will decide which index to query on a per-request basis.

API:

- [x] Modify the API prefix to be name-only, and split traffic on version
- [x] Fork the WorksController and underlying models for v1 and v2 (#1887)
- [x] Fork the SwaggerController for v1 and v2 (#1887)
- [x] Make the API read two different indexes based on the version in the path (#1899)

Ingestor:

- [x] Add logic to the ingestor to decide if a work goes to v1 or v1+v2 (#1907)
- [x] ~Fork the Elasticsearch mapping,~ add logic to the ingestor to create both mappings on startup (#1907)
- [x] Modify the ingestor to write to as many indexes as necessary (#1907)

Snapshot pipeline:

- [x] Configure the snapshot scheduler to schedule snapshots of both indexes (#1895)
- [x] Modify the elasticdump container to send an SNS message upon completion (#1895)
- [x] Delete the S3 bucket notifications and the snapshot_convertor_job_generator Lambda (#1895)
- [x] Modify the snapshot_convertor to convert something into a V1 or V2 snapshot (#1906)

**Comment by alicefuzier** [comment]
I don't think we need to fork the elasticsearch mapping, because we are not versioning the internal model, only the DisplayModels

**Comment by alexwlchan** [comment]
Oops. 🙈
