### ISSUE TITLE
After-action review items after accidentally deleting most of the Loris source images

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#1878]
- [x] Move the CloudFront logs bucket into the shared_infra stack (#1886)
- [x] Put all data stores/assets/buckets in their own file (#1880)
- [x] Restrict delete/modify S3/DynamoDB/RDS permissions for devs (https://github.com/wellcometrust/platform-private/pull/24)
- [x] Get a report of additional 404s during the outage
- [x] Add alarms on high CloudFront error rates (#1893)
