### ISSUE TITLE
Use the new mergeCandidates field for deciding matcher/merger results

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2277]
- [x] Add the new field to the model (#2265)
- [x] Populate the new field in the transformer (#2304 )
- [x] Modify the matcher to read from this field (#2300 )
