### ISSUE TITLE
Prototype Archive ingest/archive/retrieval

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#2495]
- [x] Storage API - Ingest #2531 
- [x] Verification #2434 
- [x] Registration of storage manifest #2532
- [x] Storage API - Get manifest #2475
