### ISSUE TITLE
Changes to image locations and licenses

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#2790]
Based on our discussion with Christie yesterday:

* [x] All A, B and N images which are in cold store or none with CC use restrictions should be copied to Tandem Vault. (#2857)

* [x] All images with “WIA winner only for use in WIA context” should be copied to TV. (#2855)

* [x] All remaining A, B and N images that don’t have “images withdrawn” should be copied to Tandem Vault. (#2858)

* [x] All L images, and which have “Archives {and,&} Manuscripts” in the image_library_dept field, should be copied to Tandem Vault if they're not already in TV or the API. (#2873)
* [x] All L images from between May to November 2017 should be copied to TV, especially if they're not anywhere.

* [x] All images with “science museum london” in the metadata should be copied to Tandem Vault if they're not already there. This includes images in the Catalogue API.

* [x] All images in the “New destination by image #” tab should be copied to their new location.
* [x] All images matched by the “Changes by contributor code” tab should be copied to their new location.

* [x] All images with licence changes needed should be updated.

* [x] All images with metadata changes needed should be updated.

* [ ] All failed C images should be investigated.

* [x] All Calm ID images that are CC licensed, cleared for general use and copyright, should be copied to the API. All remaining Calm ID images should go to Tandem Vault.

* [x] Provide a list of images that should be put into the Catalogue API or Tandem Vault, but we can't.

* [x] N images didn’t get added to the right collection. e.g. https://wellcome.tandemvault.com/browse/wellcome-image-awards-2017#40894343 (#2856)

**Comment by alexwlchan** [comment]
I have 153 L images added since May that aren’t already in Tandem Vault:

```
L0088955
L0088956
L0088957
L0088958
L0088959
L0088960
L0088961
L0088962
L0088963
L0088964
L0088965
L0088966
L0088971
L0088972
L0088973
L0088974
L0088975
L0088976
L0088977
L0089217
L0089687
L0089688
L0089689
L0089690
L0089719
L0089721
L0089722
L0089723
L0089724
L0089725
L0089726
L0089727
L0089728
L0089729
L0089730
L0089731
L0089732
L0089733
L0089734
L0089735
L0089736
L0089737
L0089738
L0089739
L0089740
L0089741
L0089742
L0089743
L0089744
L0089745
L0089746
L0089747
L0089748
L0089749
L0089750
L0089751
L0089752
L0089753
L0089754
L0089755
L0089756
L0089757
L0089758
L0089759
L0089760
L0089761
L0089762
L0089763
L0089764
L0089765
L0089766
L0089767
L0089768
L0089769
L0089770
L0089771
L0089772
L0089773
L0089774
L0089775
L0089776
L0089777
L0089778
L0089779
L0089780
L0089781
L0089782
L0089783
L0089784
L0089785
L0089786
L0089787
L0089788
L0089789
L0089790
L0089791
L0089792
L0089793
L0089794
L0089795
L0089796
L0089797
L0089798
L0089799
L0089800
L0089801
L0089802
L0089803
L0089804
L0089805
L0089806
L0089807
L0089808
L0089809
L0089810
L0089811
L0089812
L0089813
L0089814
L0089815
L0089816
L0089817
L0089818
L0089819
L0089820
L0089821
L0089822
L0089823
L0089824
L0089825
L0089826
L0089827
L0089828
L0089829
L0089830
L0089831
L0089832
L0089833
L0089834
L0089835
L0089836
L0089837
L0089838
L0089839
L0089840
L0089841
L0089842
L0089843
L0089844
L0089845
L0089846
L0089847
L0089848
```
