### ISSUE TITLE
Provide bag manifests as per RFC

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#2844]
https://github.com/wellcometrust/platform/tree/master/docs/rfcs/002-archival_storage#api-1

**TODO:**

- [ ] Update registrar to store all data necessary (tag-manifest excluded).
- [x] Create `registrar-http` service mirroring `progress-async` pattern to provide translation to display body and control access to progress dynamo table.
- [x] /bags API should present bag manifest with JSON-LD context and types.
