### ISSUE TITLE
Move Miro images to new locations

### ISSUE THREAD

**Issue by alexwlchan** [wellcometrust/platform#2853]
Based on our discussion with Christie yesterday:

* [ ] All A, B and N images which are in cold store or none with CC use restrictions should be copied to Tandem Vault. (#2857)

* [x] All images with “WIA winner only for use in WIA context” should be copied to TV. (#2855)

* [ ] All remaining A, B and N images that don’t have “images withdrawn” should be copied to Tandem Vault. (#2858)

* [ ] All L images, and which have “Archives {and,&} Manuscripts” in the image_library_dept field, should be copied to Tandem Vault if they're not already in TV or the API. 
* [ ] All L images from between May to November 2017 should be copied to TV, especially if they're not anywhere.

* [ ] All images with “science museum london” in the metadata should be copied to Tandem Vault if they're not already there. This includes images in the Catalogue API.

* [ ] All images in the “New destination by image #” tab should be copied to their new location.
* [ ] All images matched by the “Changes by contributor code” tab should be copied to their new location.

* [ ] All images with licence/metadata changes needed should be updated.

* [ ] All failed C images should be investigated.

* [ ] All Calm ID images that are CC licensed, cleared for general use and copyright, should be copied to the API. All remaining Calm ID images should go to Tandem Vault.

* [ ] Provide a list of images that should be put into the Catalogue API or Tandem Vault, but we can't.

* [x] N images didn’t get added to the right collection. e.g. https://wellcome.tandemvault.com/browse/wellcome-image-awards-2017#40894343 (#2856)

**Comment by alexwlchan** [comment]
For #2790.

**Comment by pollecuttn** [comment]
Closing as duplicate of #2790
