### ISSUE TITLE
Update and test new messaging libraries in Storage service

### ISSUE THREAD

**Issue by kenoir** [wellcometrust/platform#3504]
In order to better control retry and failure operations in the storage service we should finalise https://github.com/wellcometrust/scala-messaging/pulls and incorporate the new lib into the storage service (after testing).

- [x] bag register (wellcometrust/storage-service#167)
- [x] bag replicator (wellcometrust/storage-service#166)
- [x] bag unpacker (wellcometrust/storage-service#158)
- [x] bag verifier (wellcometrust/storage-service#168)
- [x] ingests (wellcometrust/storage-service#170)
- [x] notifier (wellcometrust/storage-service#171)

**Comment by alexwlchan** [comment]
All the code changes are done. I’m going to wait for Travis to publish new versions, then deploy and check the pipeline still works.

**Comment by alexwlchan** [comment]
I've deployed the new changes and tested them; the pipeline still works.
