### ISSUE TITLE
Ingest all licensed, catalogued images & data into Catalogue API

### ISSUE THREAD

**Issue by jtweed** [wellcometrust/platform#517]
Miro will become unavailable on **November 6th**, this work **must** be completed and available to the public by then.

Remaining work to transition all images to catalogue API where appropriate.

_Obtain rules for collection:_

- [x] A: contrib rules
- [x] B: contrib rules
- [X] C: Corporate photography, **skip**
- [x] D: Cold store
- [X] F: All go to cold store
-  [X] FP: Cold store
- [X] L: rules from Christy
- [X] M: rules from Christy
- [x] N: contrib rules
- [x] S: physical slide collection - digital images v. sparse
- [X] V: rules from Christy
- [x] W: contrib rules

_Implement rules for collection:_

- [x] A
- [x] B
- [X] C: Corporate photography, **skip**
- [x] D
- [X] F: All go to cold store
- [x] FP
- [X] L
- [X] M
- [x] N
- [x] S
- [X] V
- [x] W

_Run through pipeline:_

- [x] A
- [x] B
- [X] C: Corporate photography, **skip**
- [ ] D
- [X] F: All go to cold store
- [x] FP
- [X] L
- [X] M
- [x] N
- [x] S
- [X] V
- [x] W

**Comment by alexwlchan** [comment]
I’m going to do a bit of work to check the adapter can parse the XML for every Miro record – actually doing it is left for another time!

**Comment by jtweed** [comment]
* All collections except F
* Images must be copyright cleared, cataloguing complete and have no access restrictions

**Comment by alexwlchan** [comment]
Requires #882.
